# Each new term in the Fibonacci sequence is 
# generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence 
# whose values do not exceed four million, 
# find the sum of the even-valued terms.
# x, y, z 
# 0, 1, 1, 2, 3, 5, 8, 13

def main():
    x = 0 # first num
    y = 1 # second num
    z = 0 # next num
    sum = 0
    max = 4000000

    # print(f"{x}, {y}, ", end="")

    while (z <= max):
        z = x + y
        x = y
        y = z
        if (z % 2 == 0) and (z <= max):
            sum += z
        # print(f"{z}, ", end="")
        
    print(sum)

if __name__ == "__main__":
    main()